// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncdyxylunicfeswojzfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZHl4eWx1bmljZmVzd29qemZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDA1NzAsImV4cCI6MjA2OTYxNjU3MH0.r0pFBYjw_ZvOFXiYqre80vGJmBvLcIChGhSd6OopBi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});